AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lwa-streaming-response-demo-next

  Sample SAM template for lwa-streaming-response-demo-next
Globals:
  Function:
    Timeout: 60

Resources:
  NextjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      DockerTag: v1
      DockerContext: ./
      Dockerfile: Dockerfile
